namespace MyStake.Constants.Enums
{
    public enum ErrorCode
    {
        NO_ERROR = 0,
        USER_ALREADY_EXISTS = 1,
        USER_DOES_NOT_EXIST = 2,
        INSUFFICIENT_AGENT_BALANCE = 3,
        INSUFFICIENT_USER_BALANCE = 4,
        NO_BETTING_LOG_EXIST = 5,
        DUPLICATE_TRANSACTION = 6,
        INVALID_TRANSACTION = 7,
        BALANCE_LOG_DOES_NOT_EXIST = 8,
        VENDOR_IS_UNDER_MAINTENANCE = 9,
        GAME_IS_UNDER_MAINTENANCE = 10,
        DEPRECATED_ENDPOINT = 20,
        BAD_REQUEST = 400,
        UNAUTHORIZED = 401,
        UNKNOWN_SERVER_ERROR = 500,
    }
}
